NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.dsfciwarehouse.net-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.dsfciwarehouse.net-cert.pem
    OrganizationalUnitIdentifier: peer
